### ISSUE TITLE
DirectShape Material request

### ISSUE THREAD

**Issue by l-schmidt** [dimven/SpringNodes#16]
Could you add a material input to DirectShape.ByGeometry? (like the ootb DirectShape node)

**Comment by dimven** [comment]
Unless something changes dramatically with Revit 2017, the API does not allow for any material changes for imported solids. Right now, you can only specify a material for natively generated objects and only at the time of their creation.  :(

The built-in node uses the tessellatedshapebuilder class, which breaks the input geometry into triangles and then creates a new face with a material for each triangle. That's why the resulting geometry is faceted.

**Comment by l-schmidt** [comment]
Ah, I should have known it was an API limitation... oh well. I guess if I need a material, I'll have to try and get by with FamilyInstance.

**Comment by dimven** [comment]
Just had a look at the 2017 API last night. They do have quite a few new geometry additions and it looks very promising. I think that one of them permits defining materials on import. Tho I'm not sure when I'll have the chance to study it in more detail.

**Comment by dimven** [comment]
This has been implemented in the latest version as "Springs.BrepShape.ByGeometry".
