### ISSUE TITLE
FamilyInstance.ByPoints

### ISSUE THREAD

**Issue by johnpierson** [dimven/SpringNodes#27]
This node appears to require the family instance to be placed at lest once in the model.

After some investigation, it seems that changing the code to remove the Unwrap on family type and removing the var[] inputs makes this work.
![image](https://cloud.githubusercontent.com/assets/15744724/23173934/06bd47d8-f818-11e6-807c-286e43a066c7.png)

**Comment by dimven** [comment]
Hi John,

Can I make sure you're on a recent version of springs? There was an issue a while back where the package manager went wonky and got some versions of nodes confused. you should have a line that's similar to
>if not ftype[j].IsActive : ftype[j].Activate()

that makes sure that the family type is always going to be activated.

My original logic with this node(and other nodes from sn) was to always process lists and do pseudo-lacing inside the script for improved performance. Otherwise, if you define your inputs as singletons, the python interpreter would be called individually for each item in the input list and that would affect performance negatively.

So you generally have two options - either provide one type that will be used for all instances, or provide a list of types that matches your list of points for when you want to have differing types:

![revit_2017-02-22_14-10-58](https://cloud.githubusercontent.com/assets/7148394/23199700/026c0068-f90b-11e6-9d92-454f133d0039.png)

Also we should always unwrap dynamo elements if we want to use them in the context of the api

**Comment by johnpierson** [comment]
Let me double check I will update spring nodes now.

**Comment by johnpierson** [comment]
Forgot to reply. An update and removing list nesting fixed this issue for me!
