### ISSUE TITLE
Springs.FamilyInstance.Rotation is missing

### ISSUE THREAD

**Issue by Ehsanyzd** [dimven/SpringNodes#32]
It seems like the Springs.FamilyInstance.Rotation node is missing after version 100.0.1 so if I had used it in a graph and update the package, it will go away. Is there a reason for that?

**Comment by dimven** [comment]
Hi,

That node was depreciated a while back and merged with Clockwork's Element.Location node. This was mostly because rotation is a property of a point based element's location and it just made more sense to have it together in a single node. Usually you need the element's rotation in conjunction with it's location point.

**Comment by Ehsanyzd** [comment]
Thank you for clarification.
