### ISSUE TITLE
Springs.SelectLinkedElement geometry offset

### ISSUE THREAD

**Issue by ir1141** [dimven/SpringNodes#34]
Hi

I am trying to use the node "Springs.SelectLinkedElement". It successfully identifies the linked element but the geometry reference comes through offset. Everything seems to be offset in one consistent direction (but by varying amounts).

Please see picture attached (lines generated from using "Element.GetLocation"). It works fine when I am directly in the linked model using the normal node "Select Model Element".

Is this a problem with SpringNodes or something else?

Cheers

![capture](https://user-images.githubusercontent.com/32889167/31698571-a1534b62-b41a-11e7-9ce9-16d2e50db745.PNG)

**Comment by ir1141** [comment]
I should probably mention what version of software I am using:

Revit: 2017.2.2
Dynamo: 1.2.1
SpringNodes: 121.1.1

I will try with Dynamo 1.3.x when IT is back and disables group policy so I can update Dynamo.

**Comment by dimven** [comment]
Hi,

That's the expected behavior whenever the linked file does not share the host's origin. You'll first need to pull the total transform of the link and then apply it to the linked element's geometry/location to get the final location:

![revit_2017-10-18_12-47-00](https://user-images.githubusercontent.com/7148394/31701453-1583121e-b403-11e7-865c-b2341249a076.png)

**Comment by ir1141** [comment]
Thanks for responding. I'll try that tomorrow. I did wonder about the
origin, as I put this file together to test and used center to center
positioning.

**Comment by ir1141** [comment]
It works perfect! Thanks again.
