### ISSUE TITLE
"SpringsUI.Refresh" crashes Dynamo 

### ISSUE THREAD

**Issue by CongzhengZOU** [dimven/SpringNodes#64]
Hi, there could possible be a problem with the newest Dynamo for Revit 2021. 
My PC :
Dynamo Core: 2.6.1.8786
Dynamo Revit: 2.6.1.8850
Windows 10 Business

I've created a new dynamo file with only "SpringsUI.Refresh" node, and then click Refresh. Dynamo crashed.

https://github.com/DynamoDS/Dynamo/issues/11612

**Comment by dimven** [comment]
Hi,

Unfortunately I never updated the springsUI package for Dynamo 2.x and newer. And since the introduction of view extensions, it makes even less sense to update it than before. As an alternative, I suggest you try Data-Shapes with the force-run option enabled:

![image](https://user-images.githubusercontent.com/7148394/115223272-45f47a80-a114-11eb-9ff0-b1a95f2f4c2e.png)
